// flow-typed signature: 60b89af1b99d213f10bf2e301a7e53df
// flow-typed version: <<STUB>>/parallel-webpack_v^1.6.1/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'parallel-webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'parallel-webpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'parallel-webpack/bin/run' {
  declare module.exports: any;
}

declare module 'parallel-webpack/src/createVariants' {
  declare module.exports: any;
}

declare module 'parallel-webpack/src/findConfigFile' {
  declare module.exports: any;
}

declare module 'parallel-webpack/src/loadConfigurationFile' {
  declare module.exports: any;
}

declare module 'parallel-webpack/src/webpackWorker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'parallel-webpack/bin/run.js' {
  declare module.exports: $Exports<'parallel-webpack/bin/run'>;
}
declare module 'parallel-webpack/index' {
  declare module.exports: $Exports<'parallel-webpack'>;
}
declare module 'parallel-webpack/index.js' {
  declare module.exports: $Exports<'parallel-webpack'>;
}
declare module 'parallel-webpack/src/createVariants.js' {
  declare module.exports: $Exports<'parallel-webpack/src/createVariants'>;
}
declare module 'parallel-webpack/src/findConfigFile.js' {
  declare module.exports: $Exports<'parallel-webpack/src/findConfigFile'>;
}
declare module 'parallel-webpack/src/loadConfigurationFile.js' {
  declare module.exports: $Exports<'parallel-webpack/src/loadConfigurationFile'>;
}
declare module 'parallel-webpack/src/webpackWorker.js' {
  declare module.exports: $Exports<'parallel-webpack/src/webpackWorker'>;
}
